[package]
name = "fizzbuzz-rust"
version = "0.1.0"
authors = ["Drew Dickerson <ddickerson@magmutual.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
